FROM        quay.io/aptible/alpine:3.4

ENV         RABBITMQ_VERSION=<%= ENV.fetch 'RABBITMQ_VERSION' %> \
            RABBITMQ_SHA1SUM=<%= ENV.fetch 'RABBITMQ_SHA1SUM' %> \
            RABBITMQ_MNESIA_BASE=/var/db/rabbitmq \
            DATA_DIRECTORY=/var/db \
            RABBITMQ_LOGS=- \
            RABBITMQ_SASL_LOGS=-
ENV         RABBITMQ_HOME=/srv/rabbitmq_server-${RABBITMQ_VERSION} \
            PLUGINS_DIR=/srv/rabbitmq_server-${RABBITMQ_VERSION}/plugins \
            ENABLED_PLUGINS_FILE=/srv/rabbitmq_server-${RABBITMQ_VERSION}/etc/rabbitmq/enabled_plugins
ENV         PATH=$RABBITMQ_HOME/sbin:$PATH

RUN         mkdir -p /srv && \
            cd /srv && \
            ARCHIVE="rabbitmq-server-generic-unix-${RABBITMQ_VERSION}.tar.gz" && \
            apk-install curl tar gzip bash openssl pwgen && \
            curl \
              -fsSL "https://github.com/rabbitmq/rabbitmq-server/releases/download/rabbitmq_v${RABBITMQ_VERSION//\./_}/${ARCHIVE}" \
              -o "$ARCHIVE" && \
            echo "${RABBITMQ_SHA1SUM}  ${ARCHIVE}" | sha1sum -c - && \
            apk-install python erlang erlang erlang-mnesia erlang-public-key erlang-crypto erlang-ssl \
                        erlang-sasl erlang-asn1 erlang-inets erlang-os-mon erlang-xmerl erlang-eldap && \
            tar -xzvf "$ARCHIVE" && \
            rm -f "$ARCHIVE" && \
            touch "${RABBITMQ_HOME}/etc/rabbitmq/enabled_plugins" && \
            "${RABBITMQ_HOME}/sbin/rabbitmq-plugins" enable --offline rabbitmq_management && \
            apk del --purge tar gzip && \
            mkdir "$DATA_DIRECTORY"

COPY        etc/openssl.cnf /ssl/testca/openssl.cnf
COPY        etc/rabbitmq.config "${RABBITMQ_HOME}/etc/rabbitmq/"
COPY        etc/rabbitmqadmin.conf /usr/local/bin/rabbitmqadmin.conf
COPY        bin/run-database.sh /usr/bin/wrapper
COPY        bin/initialize-certs.sh /usr/bin/initialize-certs
COPY        bin/rabbitmqadmin /usr/local/bin/rabbitmqadmin

RUN         VERSION="<%= ENV.fetch 'DELAYED_MESSAGE_EXCHANGE_VERSION' %>" \
         && SHA1SUM="<%= ENV.fetch 'DELAYED_MESSAGE_EXCHANGE_SHA1SUM' %>" \
         && PLUGINS="<%= ENV.fetch 'RABBITMQ_PLUGINS' %>" \
         && ARCHIVE="rabbitmq_delayed_message_exchange-${VERSION}.ez" \
         && curl -fsSL "http://www.rabbitmq.com/community-plugins/v${PLUGINS}/${ARCHIVE}" -o "$ARCHIVE" \
         && echo "${SHA1SUM}  ${ARCHIVE}" | sha1sum -c - \
         && mv "$ARCHIVE" "/srv/rabbitmq_server-${RABBITMQ_VERSION}/plugins/" \
         && rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange

RUN         ln -s /var/db/testca/cacert.pem /ssl/cacert.pem && \
            ln -s /var/db/server/cert.pem /ssl/cert.pem && \
            ln -s /var/db/server/key.pem /ssl/key.pem

ADD         test /tmp/test
RUN         bats --tap /tmp/test && apk del --purge python

EXPOSE      5671 15671
VOLUME      ["$DATA_DIRECTORY"]
ENTRYPOINT  ["/usr/bin/wrapper"]
